### ISSUE TITLE
Problem when start MM

### ISSUE THREAD

**Issue by ezar** [fewieden/MMM-voice#12]
Platform (Hardware/OS):
Reaspberry Pi 2 / Jessie Lite

Node version:
v6.10.3

MagicMirror version:
2.1.1.

Module version:
GIT CLONE

Description of the issue:
1|mm       | TypeError: this.sendSocketNotification is not a function
1|mm       |     at fs.appendFile (/home/pi/MagicMirror/modules/MMM-voice/node_helper.js:311:22)
1|mm       |     at /home/pi/MagicMirror/modules/MMM-voice/node_modules/graceful-fs/graceful-fs.js:43:10
1|mm       |     at FSReqWrap.oncomplete (fs.js:112:15)

**Comment by fewieden** [comment]
This module doesn't use `graceful-fs`, did you install that manually?

**Comment by ezar** [comment]
No. I install MMM-voice using dependencies script.

**Comment by ezar** [comment]
Nothing? Please help me!
Regards,

**Comment by ezar** [comment]
Nothing?

**Comment by fewieden** [comment]
The new release v1.0.2 should fix that problem #14

**Comment by ezar** [comment]
It works!
