### ISSUE TITLE
Can I make others commands

### ISSUE THREAD

**Issue by small-goliath** [fewieden/MMM-voice#15]
Platform (Hardware/OS): Raspberry Pi3

Node version: 4.2.1v

MagicMirror version: 2.1.2v

Module version:  I don't download this module yet.

Description of the issue:
I wanna make others command. 
Such command have their working.
( ex. turn on a light, turn on the electric fan, etc)
Can I do that?
If I can do, what should I do?

**Comment by fewieden** [comment]
You can add voice commands to your module, which actually turns on the light or the electric fan.

This guide https://github.com/fewieden/MMM-voice/blob/master/DEVELOPER.md will get you started on how to integrate commands into your module.
