### ISSUE TITLE
Error: spawn pocketsphinx_continuous ENOENT

### ISSUE THREAD

**Issue by hvkls** [fewieden/MMM-voice#16]
Platform (Hardware/OS): 
Raspberry Pi 2B
Raspbian wheezy
Linux rp3 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux

Node version: 
node v6.11.4

MagicMirror version:
magicmirror@2.1.3 (as of 2017-10-08)

Module version:
1.02 (as of 2017-10-08)

Description of the issue:
		{
			disabled: false,
			module: 'MMM-voice',
			position: 'bottom_bar',
			config: {
				microphone: 1,
				keyword: 'MAGIC MIRROR', 
				timeout: 15
			}
		},

Error: spawn pocketsphinx_continuous ENOENT
-2

The thing is, pocketsphinx_continuous itself works!

pocketsphinx_continuous -adcdev plughw:1 -inmic yes

I'm out of ideas.

**Comment by fewieden** [comment]
Can't reproduce this issue, can you please contact me on the forum via private message so we can schedule a remote desktop session? https://forum.magicmirror.builders/topic/778/mmm-voice
