### ISSUE TITLE
"Initialising"

### ISSUE THREAD

**Issue by TheRealLinzer** [fewieden/MMM-voice#17]
Platform (Hardware/OS): Raspberry Pi3
MagicMirror version: 2.1.3
Module version: 1.0.2.

Hey,
first of all many thanks for the awesome module!
I installed everything according to the readme but when I start Magic Mirror it’s displaying “Initialising…” and the mic icon has a slash through it and is blinking infinitely.
I'm using a standard usb-mic and I've already checked for the correct ID.
Using the latest MM-version and updated.

Maybe someone can help? Many thanks in advance :)

**Comment by fewieden** [comment]
can you enable `debug: true` in config and then check your logs for more information

**Comment by ccuster1995** [comment]
Having the same problem

**Comment by cowboysdude** [comment]
Did you enable debug: true in config and then check your logs for more information?  Saying it doesn't work doesn't make it easy to help you..... ;)  So in your config.js under MMM-voice put in debug: true and see what the console log and log tells you then put it here :)

**Comment by nabbi95** [comment]
> Did you enable debug: true in config and then check your logs for more information? Saying it doesn't work doesn't make it easy to help you..... ;) So in your config.js under MMM-voice put in debug: true and see what the console log and log tells you then put it here :)

ia m having same problem and i turned debug into true but nothing changes it still shows initialising.
can you tell me where can i get this log file.

**Comment by nabbi95** [comment]
even after changing debug mode to true it shows intitialising with written undefined under initialising

**Comment by fewieden** [comment]
@nabbi95 the debug flag creates a log file in the module directory

**Comment by ArroganTz** [comment]
Im sorry to reopen this issue but i cant find a fix in here and neither do any logs appear/help after i turned on debug: true. Im getting the exact same problem. Initializing.. and under that it says "undefined".

**Comment by fewieden** [comment]
@ArroganTz with debug set to true there will be a log file generated in the module directorz. What is the content of this file?

**Comment by dthomas888** [comment]
I'm having the same problem: 
error logged this.

pocketsphinx_continuous: error while loading shared libraries: libpocketsphinx.so.3: cannot open shared object file: No such file or directory

**Comment by dthomas888** [comment]
I figured it out.
run "sudo ldconfig" after installation to fix.
LD_LIBRARY_PATH needs to be configured.
