### ISSUE TITLE
Failing at the 5. Step

### ISSUE THREAD

**Issue by DonLeito** [fewieden/MMM-voice#19]
Platform (Hardware/OS): raspbian jessie

Node version: v4.0.0

MagicMirror version: v2.2.2

Description of the issue: I followed the description and everything went well till the 5 step.
Here i got this Error.
p.s. I tried to run it with as root, didn't work.
Can anyone help plsss ??

[STEP 4/5] Exporting paths |  Done
[STEP 5/5] Installing npm dependencies
npm WARN engine stylelint@7.13.0: wanted: {"node":">=4.2.1"} (current: {"node":"4.0.0","npm":"2.14.2"})
npm WARN engine jsdoc@3.5.5: wanted: {"node":">=4.2.0"} (current: {"node":"4.0.0","npm":"2.14.2"})
npm ERR! tar.unpack untar error /home/pi/.npm/pocketsphinx-continuous/1.0.0/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/eslint-plugin-import/2.8.0/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/stylelint-config-standard/16.0.0/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/eslint-config-airbnb-base/11.3.2/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/lmtool/2.0.3/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/stylelint/7.13.0/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/jsdoc/3.5.5/package.tgz
npm ERR! tar.unpack untar error /home/pi/.npm/eslint/3.19.0/package.tgz
npm ERR! Linux 4.9.35-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--productive"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! path /home/pi/MagicMirror/modules/MMM-voice/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/home/pi/MagicMirror/modules/MMM-voice/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/home/pi/MagicMirror/modules/MMM-voice/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/pi/MagicMirror/modules/MMM-voice/node_modules',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/home/pi/MagicMirror/modules/MMM-voice/node_modules/pocketsphinx-continuous',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Linux 4.9.35-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--productive"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! path npm-debug.log.0a2c13c70744073bdb743eea569c635d
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.0a2c13c70744073bdb743eea569c635d'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, open 'npm-debug.log.0a2c13c70744073bdb743eea569c635d']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.0a2c13c70744073bdb743eea569c635d' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/MagicMirror/modules/MMM-voice/npm-debug.log
[STEP 5/5] Installing npm dependencies | Failed

**Comment by fewieden** [comment]
You have a super old nodejs version, try to update and rerun it

**Comment by mirrormonark** [comment]
Already updated.
dependencies.sh: riga 90: ./autogen.sh: File or directory does not exist
dependencies.sh: riga 91: ./configure:File or directory does not exist
make: *** No target specified and no makefile found.  Shutdown.
make: ***  No rules for generating the "install" target.  Shutdown.
[STEP 3/5] Installing pocketsphinx | Done
[STEP 4/5] Exporting paths
[STEP 4/5] Exporting paths |  Done
[STEP 5/5] Installing npm dependencies
dependencies.sh: riga 106: cd: /root/MagicMirror/modules/MMM-voice: File or directory does not exist
npm error code ENOENT
npm error syscall open
npm error path /root/pocketsphinx/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/root/pocketsphinx/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /root/.npm/_logs/2025-07-02T17_26_04_387Z-debug-0.log
[STEP 5/5] Installing npm dependencies | Failed

i was to cd MagicMirror/cd MMM-voice/cd installers/ bash dependecies.sh and i have problem with STEP3 so i restart command with sudo bash dependecies.sh but now i have error step 5
