### ISSUE TITLE
Error during 

### ISSUE THREAD

**Issue by MarBol95** [fewieden/MMM-voice#22]
Platform (Hardware/OS):
Raspian
Node version:
v9.11.1
Module version:
v1.0.2
Description of the issue:
When I start the module, it goes from "Initialisieren..." to "ERROR". 
I start the MagicMirror with "npm start" and the command line doesn't throw any errors. Just:
MMM-voice: Checking files.
MMM-voice: Starting pocketsphinx.
So everything looks alright to me. 
My microphone is conected via usb and works fine. 

I tried all the solutions from other issues but it just doesn't work. I would appreciate any kind of help! 

Thanks in advance!

**Comment by fewieden** [comment]
did you had a look in the error llog of the module itself? there should be a file in your module directory.

**Comment by marktillo** [comment]
i'm stuck at flashing mic initialising error log is 1,1 any suggestions

**Comment by fewieden** [comment]
@marktillo try to enable debug mode in the config and check the debug log for more informations

```
config: {
  debug: true
}
```

**Comment by capic** [comment]
Hi, 

I've got the same issue.
With debug mode activate, we can see that  pocketsphinx doesn't find libpocketsphinx.so.3 library. _(pocketsphinx_continuous: error while loading shared libraries: libpocketsphinx.so.3: cannot open shared object file: No such file or directory)_
So before use npm start I did LD_LIBRARY_PATH=/usr/local/lib/ (/usr/local/lib/ is the path where the library is), and now it's working

**Comment by fewieden** [comment]
@capic don't forget to deactivate the debug option again, as it will generate a huge file and will slow down your magicmirror at one point

**Comment by nabbi95** [comment]
i already have this location setted as you said but it still showing error
