### ISSUE TITLE
ERROR: "dict.c"

### ISSUE THREAD

**Issue by TheWobbyDobbyDobDob** [fewieden/MMM-voice#26]
Platform (Hardware/OS): Raspberry Pi 3

Node version: v9.11.2

MagicMirror version: newest 

Module version: newest

Description of the issue: Hey guys, after installing the module I had an Error 127 with the library problem that was already discussed. After spending the last two days ( I´m an absolute beginner) I "fixed" it. Now It says "1" in the error.log and the following in the debug.log:

![debug log of error](https://user-images.githubusercontent.com/42585959/44422056-77db6a80-a582-11e8-8774-f86259768dff.jpg)

hope you can help me.

**Comment by TheWobbyDobbyDobDob** [comment]
and I use the latest Raspbian Stretch OS

**Comment by fewieden** [comment]
@TheWobbyDobbyDobDob can you please tell me what files you have in the MMM-voice directory?

**Comment by TheWobbyDobbyDobDob** [comment]
the following:

Bytes.js
CHANGELOG.md
debug.log
DEVELOPER.md
error.log
jsdoc.json
LICENSE
MMM-voice.css
MMM-voice.js
node_helper.js
package.json
README.md
words.json

**Comment by fewieden** [comment]
Ok, for some reason it wasn't creating `MMM-voice.dic` and `MMM-voice.lm` files. Can you try to delete `words.json`, the `error.log` and the `debug.log` and then restart the mirror?

**Comment by TheWobbyDobbyDobDob** [comment]
thanks for the tip, now it works 👍. But it doen´t seem to understand what I´m saying  :/

**Comment by fewieden** [comment]
The mirror can only understand a certain amount of words, listed in the words.json. What are you trying to do, what are you saying and what is the mirror displaying that he recognizes?

**Comment by TheWobbyDobbyDobDob** [comment]
Well after a few tries the mirror recognices the key word "MagicMirror" but afterwards I tried the IP application you developed and iht didn´t get any of the commands :/ could it simply be the microphone? it was quite cheap

**Comment by fewieden** [comment]
Some people reported microphones, other had issues with their accents. One guy told me that he is even using a text2speech app on his phone because the mirror cant understand him.

**Comment by fewieden** [comment]
Closed due to inactivity
