### ISSUE TITLE
Struggling to install dependancies

### ISSUE THREAD

**Issue by Grahamrich1** [fewieden/MMM-voice#27]
Platform (Hardware/OS):

Node version:

MagicMirror version:

Module version:

Description of the issue:

**Comment by Grahamrich1** [comment]
Using a Raspberry Pi 3.
When running "bash dependencies.sh" it gets to STEP 3/5.  Around 12% (1556/12294), 22.88 MiB 2.08 Mib/s it hangs.  I've hand some concerns over my internet connection in the last few days but it stops at the same place every time.  It appears I have plenty of disk space left.

My only other observation is that I have a good number of modules installed for MMM.

**Comment by fewieden** [comment]
Could you give more details about your os?

**Comment by fewieden** [comment]
Closed due to inactivity.
