### ISSUE TITLE
Getting Error on Electron

### ISSUE THREAD

**Issue by mrronzy123** [fewieden/MMM-voice#37]
![screenshot_20181128-001115](https://user-images.githubusercontent.com/45402479/49104085-22aaa580-f2a3-11e8-9506-56e8d0618f33.jpg)
Platform (Hardware/OS): pi3b+

Description of the issue:
The installation went pretty smooth. No errors. I added the config as follows :
{
    module: 'MMM-voice',
    position: 'bottom_bar',
    config: {
        microphone: 1,
    }
},

Getting Error besides the voice icon on electron.

**Comment by fewieden** [comment]
Can you please check the error log in the module directory and post the content here.
