### ISSUE TITLE
Error on MM but no error in terminal

### ISSUE THREAD

**Issue by shadymakar** [fewieden/MMM-voice#43]
Platform (Hardware/OS): RSP

Node version:

MagicMirror version:

Module version:

Description of the issue:
![IMG_7124](https://user-images.githubusercontent.com/41170147/56086826-9d6bfb80-5e13-11e9-9e27-63caf70ab018.jpeg)
![IMG_7125](https://user-images.githubusercontent.com/41170147/56086827-9d6bfb80-5e13-11e9-80f1-7bacc97649cf.jpeg)

**Comment by fewieden** [comment]
@shadymakar errors are logged into an error log file inside the MMM-voice directory. If zou enable the debug mode in config `debug: true` it will also create a more detailed log file inside the module directory
