### ISSUE TITLE
Getting ERROR next to mic when running MagicMirror

### ISSUE THREAD

**Issue by jmart1009** [fewieden/MMM-voice#46]
Platform (Hardware/OS):Stretch

Node version:

MagicMirror version: 2.8

Module version:newest

Description of the issue:No matter what i do the software doesn't seem to be able to pic up my mic or something, have troubleshooted a lot on the MM forum, but just can't seem to get it to work. My mic works and have tested it as plughw:1,0, and i have changed the mic config in the files to be that way, but it still won't work. Don't know if there is another issue or not but would greatly appreciate help. Thanks in advance.
[debug.log](https://github.com/fewieden/MMM-voice/files/3668510/debug.log)
[error.log](https://github.com/fewieden/MMM-voice/files/3668513/error.log)

**Comment by fewieden** [comment]
The error that is thrown is (bottom of the debug log):

```
Error opening audio device plughw:1,0 for capture: Invalid argument
FATAL: "continuous.c", line 245: Failed to open audio device
```

Failed to open audio device often is raised because something else on the pi is using the mic already. Make sure nothing else is using it and retry.

**Comment by mujeebishaque** [comment]
I have checked no other process is using the mic, but it still doesn't work. I've tried changing the microphone attribute to 0 and 1, doesn't work either.

**Comment by bjorndegroot** [comment]
Can anybody help with this issue? I've the same here.

**Comment by fewieden** [comment]
@bjorndegroot what's inside your error and debug log?

EDIT: According to your issue on the forum (not active there) you could try https://forum.magicmirror.builders/post/35364 which helped a lot of users.
