### ISSUE TITLE
hi i have a problem with modules, when i run it, i have no responde,  ( i have mic and speaker, but with other modules is working)

### ISSUE THREAD

**Issue by alexbjjsoul** [fewieden/MMM-voice#47]
Platform (Hardware/OS):

Node version:

MagicMirror version:

Module version:

Description of the issue:

**Comment by alexbjjsoul** [comment]
Plataforma (Hardware / OS): rasberry pi , raspian

Versión de nodo:

Versión de MagicMirror: 2

Versión del módulo: MMM-voice

Descripción del problema:hola tengo un problema con los módulos, cuando lo ejecuto no tengo respuesta (tengo micrófono y altavoz, pero con otros módulos funciona

**Comment by fewieden** [comment]
@alexbjjsoul I'm sorry but I can only provide support in English.

- What do you mean with you have no response?
- With which modules is it working?
