### ISSUE TITLE
No Action on saying the Commands

### ISSUE THREAD

**Issue by GuntasKapoor** [fewieden/MMM-voice#48]
Platform (Hardware/OS):

Node version:

MagicMirror version:

Module version:

Description of the issue:
When i say the keyword the mic starts blinking but when i say the command there isn't any action.

**Comment by fewieden** [comment]
@GuntasKapoor sry for the late reply.

- Did you check the log files (error and debug)?
- Which command are you trying to use?

**Comment by gur01052000** [comment]
i am also facing the same issue...... please help

**Comment by fewieden** [comment]
@gur01052000 without more information I can't help. Can you please provide the debug and error log?
