### ISSUE TITLE
MMM-voice Error

### ISSUE THREAD

**Issue by RhodanBull** [fewieden/MMM-voice#49]
Platform (Hardware/OS): Raspberry Pi4B

Node version:

MagicMirror version: 2.14.0

Module version: #14 

Description of the issue: pocketsphinx_continuous: error while loading shared libraries: libpocketsphinx.so.3: cannot open shared object file: No such file or directory
This is the only i was able to get out of debug.log
If i can provide more information, please ask

**Comment by fewieden** [comment]
@RhodanBull you can check if the path is correctly set in the bashrc file. If not then you can execute the following step which helped a lot of users https://forum.magicmirror.builders/topic/778/mmm-voice/259

**Comment by RhodanBull** [comment]
The path is set correctly and with deactivating pulseaudio the error is solved.
However, i got a new one.
error.log = 1


Error opening audio device plughw:0 for capture: No such file or directory
FATAL: "continuous.c", line 245: Failed to open audio device

I read in the MM-Forum that i have to disable pulseaudio to get it working but it seems that this is not helping

Do you have an idea?

**Comment by fewieden** [comment]
@RhodanBull the pi can't find the specified microphone. I suggest testing first your setup on the pi itself before you continue debugging with MMM-voice.

Try those commands and see if you can record your voice and if the recorded sound playback is correct. Make sure to set the correct device https://learn.adafruit.com/usb-audio-cards-with-a-raspberry-pi/recording-audio

You can see your available devices with `cat /proc/asound/cards`

**Comment by RhodanBull** [comment]
For some reason my Raspi changed the audio adapters. So i was using the wrong number there.

Thanks for the help it´s working now :)

Best regards
