### ISSUE TITLE
ERROR on loading Module

### ISSUE THREAD

**Issue by moFries** [fewieden/MMM-voice#8]
Hi,

today I tried to run your module, but all I get is an error messsage on my mirror:

Message on mirror (gif):
![voice_error](https://cloud.githubusercontent.com/assets/27133126/24836445/39530344-1d1c-11e7-87a5-9a7c38a23a2e.gif)

Message on terminal:
![error_voice](https://cloud.githubusercontent.com/assets/27133126/24836446/3bce1758-1d1c-11e7-9e63-e15271e3aeb2.PNG)

I took a look in error.log, it says "**127**".

First I thought, my microphone is not found, but: 

```pi@rp_mm:~/MagicMirror $ cat /proc/asound/cards
 0 [ALSA           ]: bcm2835 - bcm2835 ALSA
                      bcm2835 ALSA
 1 [Device         ]: USB-Audio - USB PnP Sound Device
                      C-Media Electronics Inc. USB PnP Sound Device at usb-3f980000.usb-1.4, full
```

Config is:
>                 {
>                         module: 'MMM-voice',
>                         position: 'bottom_bar',
>                         config: {
>                                 microphone: 1,
>                                 // ...
>                         }
>                 },

So my question is: Do you have an idea, why it' not working. I wasn't able to find out, what error "127" could mean.

Thx in advance

moFries

**Comment by fewieden** [comment]
those errors come from pocketsphinx itself.

Can you check the debug log with enabling `debug: true` in the config?

**Comment by moFries** [comment]
Das gesamte Ergebnis steht weiter unten.

Das wichtigste war wohl: `Error opening audio device plughw:1 for capture: Device or resource busy`

Ich konnte mir nicht vorstellen, wieso das sein konnte. Naja, ich habe dann einmal in der GUI das MIkrofin als "Default" ausgewählt und voila, beim nächsten Start ging es. Ich werde es jetzt mal beobachten, wie es sich weiterentwickelt die Tage. 

Vielen Dank schon mal.

> INFO: pocketsphinx.c(152): Parsed model-specific feature parameters from /usr/local/share/pocketsphinx/model/en-us/en-us/feat.params
> Current configuration:
> [NAME]			[DEFLT]		[VALUE]
> -agc			none		none
> -agcthresh		2.0		2.000000e+00
> -allphone				
> -allphone_ci		yes		yes
> -alpha			0.97		9.700000e-01
> -ascale			20.0		2.000000e+01
> -aw			1		1
> -backtrace		no		no
> -beam			1e-48		1.000000e-48
> -bestpath		yes		yes
> -bestpathlw		9.5		9.500000e+00
> -ceplen			13		13
> -cmn			live		batch
> -cmninit		40,3,-1		41.00,-5.29,-0.12,5.09,2.48,-4.07,-1.37,-1.78,-5.08,-2.05,-6.45,-1.42,1.17
> -compallsen		no		no
> -debug					0
> -dict					modules/MMM-voice/MMM-voice.dic
> -dictcase		no		no
> -dither			no		no
> -doublebw		no		no
> -ds			1		1
> -fdict					
> -feat			1s_c_d_dd	1s_c_d_dd
> -featparams				
> -fillprob		1e-8		1.000000e-08
> -frate			100		100
> -fsg					
> -fsgusealtpron		yes		yes
> -fsgusefiller		yes		yes
> -fwdflat		yes		yes
> -fwdflatbeam		1e-64		1.000000e-64
> -fwdflatefwid		4		4
> -fwdflatlw		8.5		8.500000e+00
> -fwdflatsfwin		25		25
> -fwdflatwbeam		7e-29		7.000000e-29
> -fwdtree		yes		yes
> -hmm					/usr/local/share/pocketsphinx/model/en-us/en-us
> -input_endian		little		little
> -jsgf					
> -keyphrase				
> -kws					
> -kws_delay		10		10
> -kws_plp		1e-1		1.000000e-01
> -kws_threshold		1e-30		1.000000e-30
> -latsize		5000		5000
> -lda					
> -ldadim			0		0
> -lifter			0		22
> -lm					modules/MMM-voice/MMM-voice.lm
> -lmctl					
> -lmname					
> -logbase		1.0001		1.000100e+00
> -logfn					
> -logspec		no		no
> -lowerf			133.33334	1.300000e+02
> -lpbeam			1e-40		1.000000e-40
> -lponlybeam		7e-29		7.000000e-29
> -lw			6.5		6.500000e+00
> -maxhmmpf		30000		30000
> -maxwpf			-1		-1
> -mdef					
> -mean					
> -mfclogdir				
> -min_endfr		0		0
> -mixw					
> -mixwfloor		0.0000001	1.000000e-07
> -mllr					
> -mmap			yes		yes
> -ncep			13		13
> -nfft			512		512
> -nfilt			40		25
> -nwpen			1.0		1.000000e+00
> -pbeam			1e-48		1.000000e-48
> -pip			1.0		1.000000e+00
> -pl_beam		1e-10		1.000000e-10
> -pl_pbeam		1e-10		1.000000e-10
> -pl_pip			1.0		1.000000e+00
> -pl_weight		3.0		3.000000e+00
> -pl_window		5		5
> -rawlogdir				
> -remove_dc		no		no
> -remove_noise		yes		yes
> -remove_silence		yes		yes
> -round_filters		yes		yes
> -samprate		16000		1.600000e+04
> -seed			-1		-1
> -sendump				
> -senlogdir				
> -senmgau				
> -silprob		0.005		5.000000e-03
> -smoothspec		no		no
> -svspec					0-12/13-25/26-38
> -tmat					
> -tmatfloor		0.0001		1.000000e-04
> -topn			4		4
> -topn_beam		0		0
> -toprule				
> -transform		legacy		dct
> -unit_area		yes		yes
> -upperf			6855.4976	6.800000e+03
> -uw			1.0		1.000000e+00
> -vad_postspeech		50		50
> -vad_prespeech		20		20
> -vad_startspeech	10		10
> -vad_threshold		3.0		3.000000e+00
> -var					
> -varfloor		0.0001		1.000000e-04
> -varnorm		no		no
> -verbose		no		no
> -warp_params				
> -warp_type		inverse_linear	inverse_linear
> -wbeam			7e-29		7.000000e-29
> -wip			0.65		6.500000e-01
> -wlen			0.025625	2.562500e-02
> 
> INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='batch', VARNORM='no', AGC='none'
> INFO: acmod.c(162): Using subvector specification 0-12/13-25/26-38
> INFO: mdef.c(518): Reading model definition: /usr/local/share/pocketsphinx/model/en-us/en-us/mdef
> INFO: mdef.c(531): Found byte-order mark BMDF, assuming this is a binary mdef file
> INFO: bin_mdef.c(336): Reading binary model definition: /usr/local/share/pocketsphinx/model/en-us/en-us/mdef
> INFO: bin_mdef.c(516): 42 CI-phone, 137053 CD-phone, 3 emitstate/phone, 126 CI-sen, 5126 Sen, 29324 Sen-Seq
> INFO: tmat.c(149): Reading HMM transition probability matrices: /usr/local/share/pocketsphinx/model/en-us/en-us/transition_matrices
> INFO: acmod.c(113): Attempting to use PTM computation module
> INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /usr/local/share/pocketsphinx/model/en-us/en-us/means
> INFO: ms_gauden.c(242): 42 codebook, 3 feature, size: 
> INFO: ms_gauden.c(244):  128x13
> INFO: ms_gauden.c(244):  128x13
> INFO: ms_gauden.c(244):  128x13
> INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /usr/local/share/pocketsphinx/model/en-us/en-us/variances
> INFO: ms_gauden.c(242): 42 codebook, 3 feature, size: 
> INFO: ms_gauden.c(244):  128x13
> INFO: ms_gauden.c(244):  128x13
> INFO: ms_gauden.c(244):  128x13
> INFO: ms_gauden.c(304): 222 variance values floored
> INFO: ptm_mgau.c(476): Loading senones from dump file /usr/local/share/pocketsphinx/model/en-us/en-us/sendump
> INFO: ptm_mgau.c(500): BEGIN FILE FORMAT DESCRIPTION
> INFO: ptm_mgau.c(563): Rows: 128, Columns: 5126
> INFO: ptm_mgau.c(595): Using memory-mapped I/O for senones
> INFO: ptm_mgau.c(838): Maximum top-N: 4
> INFO: phone_loop_search.c(114): State beam -225 Phone exit beam -225 Insertion penalty 0
> INFO: dict.c(320): Allocating 4135 * 20 bytes (80 KiB) for word entries
> INFO: dict.c(333): Reading main dictionary: modules/MMM-voice/MMM-voice.dic
> INFO: dict.c(213): Dictionary size 34, allocated 0 KiB for strings, 0 KiB for phones
> INFO: dict.c(336): 34 words read
> INFO: dict.c(358): Reading filler dictionary: /usr/local/share/pocketsphinx/model/en-us/en-us/noisedict
> INFO: dict.c(213): Dictionary size 39, allocated 0 KiB for strings, 0 KiB for phones
> INFO: dict.c(361): 5 words read
> INFO: dict2pid.c(396): Building PID tables for dictionary
> INFO: dict2pid.c(406): Allocating 42^3 * 2 bytes (144 KiB) for word-initial triphones
> INFO: dict2pid.c(132): Allocated 21336 bytes (20 KiB) for word-final triphones
> INFO: dict2pid.c(196): Allocated 21336 bytes (20 KiB) for single-phone word triphones
> INFO: ngram_model_trie.c(354): Trying to read LM in trie binary format
> INFO: ngram_model_trie.c(365): Header doesn't match
> INFO: ngram_model_trie.c(177): Trying to read LM in arpa format
> INFO: ngram_model_trie.c(193): LM of order 3
> INFO: ngram_model_trie.c(195): #1-grams: 29
> INFO: ngram_model_trie.c(195): #2-grams: 54
> INFO: ngram_model_trie.c(195): #3-grams: 27
> INFO: lm_trie.c(474): Training quantizer
> INFO: lm_trie.c(482): Building LM trie
> INFO: ngram_search_fwdtree.c(74): Initializing search tree
> INFO: ngram_search_fwdtree.c(101): 31 unique initial diphones
> INFO: ngram_search_fwdtree.c(186): Creating search channels
> INFO: ngram_search_fwdtree.c(323): Max nonroot chan increased to 168
> INFO: ngram_search_fwdtree.c(333): Created 31 root, 40 non-root channels, 5 single-phone words
> INFO: ngram_search_fwdflat.c(157): fwdflat: min_ef_width = 4, max_sf_win = 25
> INFO: continuous.c(307): pocketsphinx_continuous COMPILED ON: Apr  9 2017, AT: 11:29:15
>
> Error opening audio device plughw:1 for capture: Device or resource busy
> FATAL: "continuous.c", line 245: Failed to open audio device

**Comment by trussellaaa** [comment]
I'm having the same problem - exactly as above.

**Comment by rcuart** [comment]
I got the same ERROR in the screen and when i try to debug with "debug;true" a "undefined" message appear behind the "ERROR" one.

**Comment by fewieden** [comment]
@trussellaaa @rcuart the translated solution of @moFries was to set the microphone in the pi gui to default

@rcuart if debug is enabled the undefined message is expected before any voice is recognized, but as you have an error this will not change. can you share your debug.log file

**Comment by rcuart** [comment]
@fewieden thanks for your fast answer!
Here's my 'debug.log' file:
`pocketsphinx_continuous: error while loading shared libraries: libpocketsphinx.so.3: cannot open shared object file: No such file or directory`

**Comment by fewieden** [comment]
It cannot find the installation of pocketsphinx.
Can you check your bashrc file if there is the following entry at the bottom?
```
LD_LIBRARY_PATH=/usr/local/lib
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
```
Did you run the installer with sudo rights?

**Comment by rcuart** [comment]
mmm i'll try to reinstall with sudo rights.
I'm giving feedback this evening!

Thanks.

**Comment by rcuart** [comment]
`[STEP 3/6] Installing pocketsphinx | Done
[STEP 4/6] Exporting paths
[STEP 4/6] Exporting paths |  Done
[STEP 5/6] Installing npm dependencies
dependencies.sh: línea 106: cd: /root/MagicMirror/modules/MMM-voice: No existe el fichero o el directorio
npm WARN enoent ENOENT: no such file or directory, open '/root/pocketsphinx/package.json'
npm WARN pocketsphinx No description
npm WARN pocketsphinx No repository field.
npm WARN pocketsphinx No README data
npm WARN pocketsphinx No license field.
[STEP 5/6] Installing npm dependencies | Done
[STEP 6/6] Manipulating dependencies
dependencies.sh: línea 118: cd: /root/MagicMirror/modules/MMM-voice/node_modules/pocketsphinx-continuous: No existe el fichero o el directorio
sed: no se puede leer index.js: No existe el fichero o el directorio
[STEP 6/6] Manipulating dependencies | Failed
`

**Comment by fewieden** [comment]
I just asked if you did it. Reason is that you shouldn't do it :D

**Comment by rcuart** [comment]
Right! The problem is that i realized i was wrong too late -_-.
Now making a clean install of the OS, mirror and then the module.

**Comment by rcuart** [comment]
Now i got the error '127' too.
Debug:

`pocketsphinx_continuous: error while loading shared libraries: libpocketsphinx.so.3: cannot open shared object file: No such file or directory
`

**Comment by rcuart** [comment]
SOLVED:
`LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib`
`sudo ldconfig`

More info: [http://stackoverflow.com/questions/4743233/is-usr-local-lib-searched-for-shared-libraries](url)

**Comment by fewieden** [comment]
the installer should have placed that in the bashrc in the first place

**Comment by marktillo** [comment]
Does anyone have a solution to setting up and using a eye toy as the mic all I get is initialise, waiting for mode, then error

**Comment by fewieden** [comment]
@marktillo you might want to get in touch with someone here https://forum.magicmirror.builders/ I know that several people on the forum are using ps3 eye camera

**Comment by shazglas02** [comment]
How do I uninstall MMM-voice as it just shows an ERROR even after running the commands you mentioned above!?

**Comment by fewieden** [comment]
@shazglas02 https://forum.magicmirror.builders/topic/778/mmm-voice/101

**Comment by Jacobphilli** [comment]
@rcuart @fewieden 

An above comment says this: 

“SOLVED:
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
sudo ldconfig

More info: http://stackoverflow.com/questions/4743233/is-usr-local-lib-searched-for-shared-libraries”

I looked at the link included but it’s still not clear what I should do. I’m also receiving this error message and would like to fix it. 

Could you help me out? Thanks!

**Comment by fewieden** [comment]
Execute those two commands in your terminal

**Comment by nabbi95** [comment]
still not working
