### ISSUE TITLE
Background is only white

### ISSUE THREAD

**Issue by MaengMarco** [fewieden/MMM-voice#9]
I applied to MMM-voice and MMM-tts on my MagicMirror2.
But after 'npm start', background color was only white.
I tried 'magic mirror' and 'wake up' command. But it did not change.
What should I do??

**Comment by fewieden** [comment]
Do you get any errors in your terminal?
White screen occurs if the mirror cant start properly.
Did you install the module in the right path?

**Comment by fewieden** [comment]
I will close this issue for now. If your issue still persists let me know and I will reopen the issue.
